// ViV-Wallet-app/src/app/banner/banner.component.ts
import { Component, OnInit } from '@angular/core';
import { Role, User } from '../types';
import { LoginService } from '../login.service';

@Component({
    selector: 'wallet-banner',
    templateUrl: './banner.component.html',
    styleUrls: ['./banner.component.scss']
})
export class BannerComponent implements OnInit {

    user: User =
        { id: '7', login: 'tmontgomery', fullname: 'MONTGOMERY Théophile', email: 'theophile.montgomery@invivoo.com' };

    currentRoleName: string;

    constructor(private loginService: LoginService) { }

    ngOnInit() {
        switch (this.loginService.getCurrentRole()) {
            case Role.Admin:
                this.currentRoleName = 'System Administrator';
                break;
            default:
                this.currentRoleName = 'UNKNOWN';
                break;
        }

    }

}

<header>
    <a href="#" (click)="!!logout()" id="logout">Logout</a>
    <p>User: {{user.fullname}}</p>
    <p>{{currentRoleName}}</p>
</header>

// viv-wallet-app-vue/src/components/Banner.vue
<template>
    <header>
        <div id="user">
            <p>User: {{user.fullname}}</p>
            <p>{{currentRoleName}}</p>
        </div>
        <a href="#" v-on:click="logout" id="logout">Logout</a>
    </header>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { User } from "../models/user";
import { Role } from "../models/role";
import { LoginService } from "../services/login";

@Component
export default class Banner extends Vue {
    user: User =
        { id: '7', login: 'tmontgomery', fullname: 'MONTGOMERY Théophile', email: 'theophile.montgomery@invivoo.com' };
    currentRoleName: string = '';
    loginService: LoginService;

    constructor() {
        super();
        this.loginService = new LoginService();
    }

    mounted() {
        switch (this.loginService.getCurrentRole()) {
            case Role.Admin:
                this.currentRoleName = 'System Administrator';
                break;
            default:
                this.currentRoleName = 'UNKNOWN';
                break;
        }
    }

    logout() {
        this.loginService.logout();
    }
}
</script>

<style scoped>
  header {
    display: flex;
    justify-content: space-between;
  }

  #user {
    text-align: left;
    margin-left: 1em;
  }

  #logout {
    margin-right: 1em;
  }
</style>
